name: Build and Push Docker Image

on:
  push:
    branches: 
     - main  # هيشتغل كل مرة تعملي push على فرع main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout الكود
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ تسجيل الدخول على DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Build للـ image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cppapp:latest .

      # 4️⃣ Push للـ image على DockerHub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/cppapp:latest
